---
- name: install vim
  hosts: all
  user: root
  become: true

  tasks:
    - name: install vim
      ansible.builtin.apt:
        pkg:
          - vim
        state: latest
        update_cache: true
    
    - name: check /etc/password
      ansible.builtin.stat:
        path: /etc/passwd
